version: '3'

services:
  app:
    image: harfang:latest
    command: gunicorn project.wsgi --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/app:Z
    env_file: .env
    networks:
      - backend

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:Z
      - ./static:/usr/src/app/static:Z
    depends_on:
      - app
    ports:
      - "8000:80"
    networks:
      - frontend
      - backend
   
networks:
  frontend:
  backend:
