name: Publish
on:
  push:
    paths:
      - templates/**
      - translations/**
      - pelicanconf.py
      - publishconf.py
      - requirements.txt
env:
  DISTRIBUTION_ID: ${{ secrets.DISTRIBUTION_ID }}
  CONTACT_ENDPOINT: ${{ secrets.CONTACT_ENDPOINT }}
permissions:
  id-token: write
  contents: read
jobs:
  S3PackageUpload:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_GITHUB_ROLE }}
          aws-region: us-east-1
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip' # caching pip dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Compile translations
        run: pybabel compile --directory translations/ --domain messages
      - name: Generate static site
        run: pelican --settings publishconf.py --quiet --output public
      - name: Inject Lambda contact form URL
        run: sed -i "s|PLACEHOLDER_CONTACT_URL|$CONTACT_ENDPOINT|" ./public/index.html ./public/fr/index.html
      - name: Upload to S3
        run: aws s3 cp ./public s3://positronweb.ca/ --recursive
      - name: Invalidate CF caches
        run: aws cloudfront create-invalidation --distribution-id "$DISTRIBUTION_ID" --paths "/*"
